# Generated by Django 5.2.5 on 2025-08-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
