# Generated by Django 5.2.5 on 2025-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0007_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('security', 'Security'), ('counseling', 'Counseling'), ('health', 'Health Services'), ('other', 'Other')], default='other', max_length=20)),
                ('phone', models.CharField(max_length=32)),
                ('alt_phone', models.CharField(blank=True, max_length=32)),
                ('is_24_7', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
